# Generated by Django 4.0.4 on 2022-05-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuariosBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=40)),
                ('contraseña', models.CharField(max_length=40)),
                ('oblea', models.CharField(max_length=40)),
                ('legajo', models.CharField(max_length=7)),
            ],
        ),
    ]
